# Generated by Django 2.1.11 on 2021-06-03 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_permission', models.CharField(choices=[('超级用户', 'root'), ('注册用户', 'user'), ('未注册用户', 'no_user')], default='user', max_length=32)),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('login_sta', models.BooleanField(default=False)),
                ('login_lock', models.DateTimeField(blank=True, null=True)),
                ('pwd_errnum', models.CharField(default='MA==', max_length=32)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=32)),
                ('user_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.Permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
                'ordering': ['c_time'],
            },
        ),
    ]
